global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "crm-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["app:9091"]
    basic_auth:
      username: "user1"
      password: "password1"
